Repository Team-Ampersand/Dotori-server, pull requests merged in 2021-11, with the labels that each got.

#167 Jenkins로 배포를 했을때 redis와 연결이 안되는 에러 해결
  Jenkinsfile
  docker-compose.yml
Labels: bug, documentation, Build Success

#168 Develop
  Dockerfile
  Jenkinsfile
  build.gradle
  docker-compose.yml
  src/main/java/com/server/Dotori/exception/basic_error/BasicErrorHandler.java
  src/main/java/com/server/Dotori/exception/basic_error/controller/BasicErrorController.java
  src/main/java/com/server/Dotori/exception/token/TokenExceptionHandler.java
  src/main/java/com/server/Dotori/exception/token/TokenExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/model/board/dto/BoardDto.java
  src/main/java/com/server/Dotori/model/board/dto/BoardGetDto.java
  src/main/java/com/server/Dotori/model/board/dto/BoardGetIdDto.java
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/controller/RefreshTokenController.java
  src/main/java/com/server/Dotori/model/member/controller/email/EmailController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/member/MemberStuInfoController.java
  src/main/java/com/server/Dotori/model/member/dto/GetAboutPointDto.java
  src/main/java/com/server/Dotori/model/member/dto/PointDto.java
  src/main/java/com/server/Dotori/model/member/dto/RoleUpdateDto.java
  src/main/java/com/server/Dotori/model/member/dto/StuNumUpdateDto.java
  src/main/java/com/server/Dotori/model/member/dto/StudentInfoDto.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenService.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailSendService.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailSendServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailService.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/music/dto/MusicApplicationDto.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/main/java/com/server/Dotori/security/SecurityConfig.java
  src/main/java/com/server/Dotori/security/exception/ExceptionHandlerFilter.java
  src/main/java/com/server/Dotori/security/exception/ExceptionHandlerFilterConfig.java
  src/main/java/com/server/Dotori/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/server/Dotori/security/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenFilter.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenFilterConfigurer.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenProvider.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: Build Success

#169 자습신청 상태조회
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/councillor/CouncillorSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/developer/DeveloperSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/member/MemberSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyService.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
Labels: enhancement, Build Success

#170 오늘 신청된 음악 조회 기능 개발
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/councillor/CouncillorSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/developer/DeveloperSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/member/MemberSelfStudyController.java
  src/main/java/com/server/Dotori/model/music/controller/admin/AdminMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: enhancement, code-review, Build Success

#171 Feature/exception message
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandler.java
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/music/exception/MusicTodayNotRequestedException.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
Labels: Build Success

#172 오늘 신청한 음악 조회 - 추가한 exception으로 변경
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
Labels: Build Success

#173 Develop
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandler.java
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/music/exception/MusicTodayNotRequestedException.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/councillor/CouncillorSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/developer/DeveloperSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/member/MemberSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyService.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/music/controller/admin/AdminMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: Build Success

#174 기상음악 누락된 주석 추가
  src/main/java/com/server/Dotori/model/music/controller/admin/AdminMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
Labels: Build Success
