Repository Team-Ampersand/Dotori-server, pull requests merged in 2021-10, with the labels that each got.

#141 xss response filter
  build.gradle
  src/main/java/com/server/Dotori/config/web/WebConfig.java
  src/main/java/com/server/Dotori/config/xss/HTMLCharacterEscapes.java
Labels: Build Success

#142 Feature/member exception taehyeon
  src/main/java/com/server/Dotori/model/board/service/BoardService.java
  src/main/java/com/server/Dotori/model/member/dto/SelfStudyStudentsDto.java
  src/main/java/com/server/Dotori/model/member/dto/StuNumUpdateDto.java
  src/main/java/com/server/Dotori/model/member/dto/StudentInfoDto.java
  src/main/java/com/server/Dotori/model/member/service/point/PointServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/model/music/dto/MusicApplicationDto.java
  src/main/java/com/server/Dotori/model/music/dto/MusicResDto.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
Labels: Build Success

#143 Develop
  build.gradle
  src/main/java/com/server/Dotori/config/web/WebConfig.java
  src/main/java/com/server/Dotori/config/xss/HTMLCharacterEscapes.java
  src/main/java/com/server/Dotori/model/board/service/BoardService.java
  src/main/java/com/server/Dotori/model/member/dto/SelfStudyStudentsDto.java
  src/main/java/com/server/Dotori/model/member/dto/StuNumUpdateDto.java
  src/main/java/com/server/Dotori/model/member/dto/StudentInfoDto.java
  src/main/java/com/server/Dotori/model/member/service/point/PointServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/model/music/dto/MusicApplicationDto.java
  src/main/java/com/server/Dotori/model/music/dto/MusicResDto.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
Labels: Build Success

#145 Feature/exception comment taehyeon
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/point/PointServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
Labels: Build Success

#144 Feature/exception message
  src/main/java/com/server/Dotori/exception/board/BoardExceptionHandler.java
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandler.java
  src/main/java/com/server/Dotori/exception/selfstudy/SelfStudyExceptionHandler.java
  src/main/java/com/server/Dotori/exception/token/TokenExceptionHandler.java
  src/main/java/com/server/Dotori/exception/token/TokenExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/token/controller/TokenExceptionController.java
  src/main/java/com/server/Dotori/exception/token/exception/TokenIsEmptyException.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandler.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/user/controller/UserExceptionController.java
  src/main/java/com/server/Dotori/exception/user/exception/UserAuthenticationKeyNotMatchingException.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
Labels: Build Success

#150 Application server 표준시 설정
  src/main/java/com/server/Dotori/DotoriApplication.java
  src/main/java/com/server/Dotori/model/member/schedule/SelfStudySchedule.java
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
Labels: Build Success

#149 즉시로딩에서 지연로딩으로 변경
  src/main/java/com/server/Dotori/model/board/Board.java
  src/main/java/com/server/Dotori/model/music/Music.java
Labels: Build Success

#151 음악, 자습신청/취소 가능 시간 지정과 검증
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/councillor/CouncillorSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/developer/DeveloperSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/member/MemberSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyService.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: code-review, Build Success

#147 비밀번호 찾기 로직 변경
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/controller/Email/EmailController.java
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberPasswordDto.java
  src/main/java/com/server/Dotori/model/member/dto/SendAuthKeyForChangePasswordDto.java
  src/main/java/com/server/Dotori/model/member/dto/VerifiedAuthKeyAndChangePasswordDto.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/service/MemberService.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailService.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
  src/test/java/com/server/Dotori/util/CurrentUserUtilTest.java
Labels: bug, documentation, code-review, correction

#153 잘못된 회원탈퇴 기능 hotfix
  src/main/java/com/server/Dotori/model/member/dto/MemberDeleteDto.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
Labels: bug, Build Success, hotfix

#157 자습신청/취소, 기상음악 신청 시간, 날짜에 따른 예외
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: Build Success

#166 사용하지 않는 import 제거 + 사용하지않는 메소드 제거
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/controller/RefreshTokenController.java
  src/main/java/com/server/Dotori/model/member/controller/email/EmailController.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenService.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailSendService.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailSendServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailService.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/main/java/com/server/Dotori/security/exception/ExceptionHandlerFilter.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenFilter.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenFilterConfigurer.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenProvider.java
Labels: Build Success, correction
