Repository Team-Ampersand/Dotori-server, pull requests merged in 2021-12, with the labels that each got.

#175 자습신청 수 카운트 다른 상황
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
Labels: Build Success, hotfix

#176 Develop
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/music/controller/admin/AdminMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
Labels: Build Success

#177 서버 AWS로 마이그레이션 하기 위해 Jenkinsfile 코드 수정
  Jenkinsfile
Labels: correction

#179 Develop
  Jenkinsfile
  src/main/java/com/server/Dotori/config/web/WebConfig.java
Labels: Build Success

#180 [UPDATE] release cors config
  src/main/java/com/server/Dotori/config/web/WebConfig.java
Labels: Build Success

#181 Develop
  src/main/java/com/server/Dotori/config/web/WebConfig.java
Labels: Build Success

#182 Feature/connect rds
  .gitignore
  build.gradle
Labels: Build Success

#185 운영서버와 개발서버의 분리
  .gitignore
  src/main/java/com/server/Dotori/config/swagger/SwaggerConfig.java
Labels: Build Success

#187 Email 서비스 AWS SES 로 마이그레이션 작업
  build.gradle
  src/main/java/com/server/Dotori/config/aws/AwsSesConfig.java
  src/main/java/com/server/Dotori/model/member/dto/SenderDto.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailSendService.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailSendServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailService.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/main/java/com/server/Dotori/util/EmailSender.java
  src/test/java/com/server/Dotori/model/member/service/email/AwsServiceTest.java
Labels: Build Success, Migration

#188 엔티티 수정 및 추가
  src/main/java/com/server/Dotori/model/member/EmailCertificate.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
Labels: bug, correction

#191 [FIX] massage -> message로 변경
  src/main/java/com/server/Dotori/response/ResponseService.java
  src/main/java/com/server/Dotori/response/result/CommonResult.java
  src/test/java/com/server/Dotori/response/ResponseServiceTest.java
Labels: Build Success

#190 Redis 레거시 청산 [1]
  src/main/java/com/server/Dotori/model/member/EmailCertificate.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/controller/RefreshTokenController.java
  src/main/java/com/server/Dotori/model/member/dto/EmailCertificateDto.java
  src/main/java/com/server/Dotori/model/member/repository/email/EmailCertificateRepository.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/point/PointServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/security/authentication/MyUserDetails.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenProvider.java
  src/main/java/com/server/Dotori/util/CurrentUserUtil.java
  src/test/java/com/server/Dotori/model/board/service/BoardServiceTest.java
  src/test/java/com/server/Dotori/model/member/MemberTest.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/point/PointServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/role/RoleServiceImplTest.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
  src/test/java/com/server/Dotori/util/CurrentUserUtilTest.java
Labels: Build Success, correction

#193 Redis 레거시 청산 [2] ( 로그인 안했을때 비밀번호 찾기 로직 편 )
  src/main/java/com/server/Dotori/model/member/dto/EmailCertificateDto.java
  src/main/java/com/server/Dotori/model/member/dto/VerifiedAuthKeyAndChangePasswordDto.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/Dotori/util/redis/RedisUtilTest.java
Labels: Build Success

#194 delete redis
  build.gradle
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/util/redis/RedisUtil.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
  src/test/java/com/server/Dotori/security/SecurityTest.java
Labels: Build Success

#195 사용되지않는 import 레거시 청산
  src/main/java/com/server/Dotori/model/BaseTimeEntity.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/dto/EmailCertificateDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/dto/SenderDto.java
  src/main/java/com/server/Dotori/model/member/dto/VerifiedAuthKeyAndChangePasswordDto.java
  src/main/java/com/server/Dotori/model/member/repository/email/EmailCertificateRepository.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailService.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/email/AwsServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
Labels: Build Success

#197 Exception 추가
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandler.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/user/exception/OverCertificateTimeException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserNoInformationException.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
Labels: Build Success

#198 Custom Exception 적용
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/security/authentication/MyUserDetails.java
  src/test/java/com/server/Dotori/util/CurrentUserUtilTest.java
Labels: Build Success

#196 Youtube URL인지 확인하는 정규표현식 추가
  src/main/java/com/server/Dotori/model/music/dto/MusicApplicationDto.java
Labels: Build Success

#199 NPE(NullPointException) 문제 해결
  src/main/java/com/server/Dotori/model/member/repository/email/EmailCertificateRepository.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
Labels: bug, Build Success

#200 유효기간이 만료되지 않았을때 해당 키가 삭제 되지 않는 에러 해결
  src/main/java/com/server/Dotori/model/member/repository/email/EmailCertificateRepository.java
  src/main/java/com/server/Dotori/util/EmailSender.java
Labels: bug, Build Success

#201 Develop
  build.gradle
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandler.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/user/exception/OverCertificateTimeException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserNoInformationException.java
  src/main/java/com/server/Dotori/model/BaseTimeEntity.java
  src/main/java/com/server/Dotori/model/member/EmailCertificate.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/controller/RefreshTokenController.java
  src/main/java/com/server/Dotori/model/member/dto/EmailCertificateDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/dto/SenderDto.java
  src/main/java/com/server/Dotori/model/member/dto/VerifiedAuthKeyAndChangePasswordDto.java
  src/main/java/com/server/Dotori/model/member/repository/email/EmailCertificateRepository.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailService.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/point/PointServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/model/music/dto/MusicApplicationDto.java
  src/main/java/com/server/Dotori/response/ResponseService.java
  src/main/java/com/server/Dotori/response/result/CommonResult.java
  src/main/java/com/server/Dotori/security/authentication/MyUserDetails.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenProvider.java
  src/main/java/com/server/Dotori/util/CurrentUserUtil.java
  src/main/java/com/server/Dotori/util/EmailSender.java
  src/main/java/com/server/Dotori/util/redis/RedisUtil.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/Dotori/model/board/service/BoardServiceTest.java
  src/test/java/com/server/Dotori/model/member/MemberTest.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/email/AwsServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/point/PointServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/role/RoleServiceImplTest.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
  src/test/java/com/server/Dotori/response/ResponseServiceTest.java
  src/test/java/com/server/Dotori/security/SecurityTest.java
  src/test/java/com/server/Dotori/util/CurrentUserUtilTest.java
  src/test/java/com/server/Dotori/util/redis/RedisUtilTest.java
Labels: code-review, Build Success

#202 client "localhost:5000" address cors permit
  src/main/java/com/server/Dotori/config/web/WebConfig.java
Labels: Build Success

#203 Develop
  src/main/java/com/server/Dotori/config/web/WebConfig.java
Labels: Build Success

#205 Exception 추가
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandler.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/user/controller/UserExceptionController.java
  src/main/java/com/server/Dotori/exception/user/exception/EmailHasNotBeenCertificateException.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
Labels: Build Success

#206 이메일 인증이 되었는지 확인하는 예외처리 추가
  src/main/java/com/server/Dotori/model/member/repository/email/EmailCertificateRepository.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
Labels: Build Success
