Repository Team-Ampersand/Dotori-server, pull requests merged in 2021-09, with the labels that each got.

#73 반별로 전체 상벌점 목록 조회
  src/main/java/com/server/Dotori/model/member/controller/point/PointController.java
  src/main/java/com/server/Dotori/model/member/dto/point/GetPointDto.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/point/PointService.java
  src/main/java/com/server/Dotori/model/member/service/point/PointServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/point/PointServiceTest.java
Labels: enhancement, code-review, Build Success

#74 selfstudy total count
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/SelfStudyController.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyService.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
Labels: enhancement, code-review, Build Success

#75 my page API
  src/main/java/com/server/Dotori/model/member/controller/mypage/MyPageController.java
  src/main/java/com/server/Dotori/model/member/dto/GetAboutPointDto.java
  src/main/java/com/server/Dotori/model/member/dto/PointDto.java
  src/main/java/com/server/Dotori/model/member/dto/SelfStudyStudentsDto.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/mypage/MyPageService.java
  src/main/java/com/server/Dotori/model/member/service/mypage/MyPageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/point/PointService.java
  src/main/java/com/server/Dotori/model/member/service/point/PointServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyService.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/mypage/MyPageServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/point/PointServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
Labels: enhancement, code-review, Build Success

#77 평일 자정 학생들의 음악신청을 변경하게 자동화
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
  src/test/java/com/server/Dotori/model/music/schedule/MusicScheduleTest.java
Labels: enhancement, code-review

#79 Feature/user
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenProvider.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
Labels: code-review, Build Success

#78 자습신청 상태 평일 새벽 2시 초기화
  src/main/java/com/server/Dotori/model/member/schedule/SelfStudySchedule.java
  src/test/java/com/server/Dotori/model/member/schedule/SelfStudyScheduleTest.java
Labels: enhancement, code-review

#80 자습신청 된 학생 학년반별 카테고리, 학번별 오름차순 정렬로 조회
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/SelfStudyController.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyService.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
Labels: enhancement, code-review, Build Success

#82 SelfStudy Dto idx 반환 추가
  src/main/java/com/server/Dotori/model/member/dto/SelfStudyStudentsDto.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryImpl.java
Labels: code-review, Build Success

#83 Develop
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/SelfStudyController.java
  src/main/java/com/server/Dotori/model/member/dto/SelfStudyStudentsDto.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/schedule/SelfStudySchedule.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyService.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenProvider.java
  src/test/java/com/server/Dotori/model/member/schedule/SelfStudyScheduleTest.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/music/schedule/MusicScheduleTest.java
Labels: Build Success

#84 board service 주석 추가
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
Labels: Build Success

#85 Music 관련 작업
  src/main/java/com/server/Dotori/model/music/controller/MusicController.java
  src/main/java/com/server/Dotori/model/music/dto/MusicResDto.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: code-review

#86 Feature/user 회원가입 로직 변경
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
Labels: bug, code-review

#88 [FIX] 로직, 설계 변경으로 인한 오류
  src/test/java/com/server/Dotori/model/board/service/BoardServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/mypage/MyPageServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/point/PointServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
  src/test/java/com/server/Dotori/security/SecurityTest.java
  src/test/java/com/server/Dotori/util/CurrentUserUtilTest.java
Labels: Build Success, hotfix

#90 음악신청 author 주석 누락된 부분 추가
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
Labels: Build Success

#89 자습신청 관련 주석
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/schedule/SelfStudySchedule.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
Labels: Build Success

#92 상벌점 주석 추가
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/point/PointServiceImpl.java
Labels: Build Success

#91 Feature/user 로그인 받는 인자값 변경
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/dto/MemberLoginDto.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
Labels: code-review

#93 Feature/user MemberPasswordDto 급히 추가
  src/main/java/com/server/Dotori/model/member/dto/MemberPasswordDto.java
Labels: Build Success, hotfix

#94 메인페이지 기능 주석추가
  src/main/java/com/server/Dotori/model/member/controller/mypage/MyPageController.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/mainpage/MainPageService.java
  src/main/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceTest.java
Labels: Build Success

#95 학생정보 변경페이지 조회
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/StuInfoController.java
  src/main/java/com/server/Dotori/model/member/dto/StudentInfoDto.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoService.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/util/ObjectMapperUtils.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
Labels: enhancement, code-review, Build Success

#97 권한변경
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/StuInfoController.java
  src/main/java/com/server/Dotori/model/member/dto/RoleUpdateDto.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoService.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
Labels: enhancement, code-review, Build Success

#98 Feature/user signup,signin 테스트 코드
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/dto/MemberLoginDto.java
  src/main/java/com/server/Dotori/model/member/service/MemberService.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
Labels: code-review, Build Success

#101 Feature/user EmailServiceImpl 의 주석 추가 + logout 기능 구현
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/service/MemberService.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
Labels: code-review, Build Success

#100 학생 정보 변경 (학번 변경)
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/dto/StuNumUpdateDto.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoService.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
Labels: enhancement, code-review, Build Success

#102 Develop
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/controller/mypage/MyPageController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/StuInfoController.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberLoginDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberPasswordDto.java
  src/main/java/com/server/Dotori/model/member/dto/RoleUpdateDto.java
  src/main/java/com/server/Dotori/model/member/dto/StuNumUpdateDto.java
  src/main/java/com/server/Dotori/model/member/dto/StudentInfoDto.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/schedule/SelfStudySchedule.java
  src/main/java/com/server/Dotori/model/member/service/MemberService.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/mainpage/MainPageService.java
  src/main/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/point/PointServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoService.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/model/music/controller/MusicController.java
  src/main/java/com/server/Dotori/model/music/dto/MusicResDto.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/main/java/com/server/Dotori/util/ObjectMapperUtils.java
  src/test/java/com/server/Dotori/model/board/service/BoardServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/point/PointServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
  src/test/java/com/server/Dotori/security/SecurityTest.java
  src/test/java/com/server/Dotori/util/CurrentUserUtilTest.java
Labels: Build Success

#103 학생정보 변경 (이름)
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/dto/UsernameUpdateDto.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoService.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
Labels: enhancement, code-review, Build Success

#104 권한조회
  src/main/java/com/server/Dotori/model/member/service/role/RoleService.java
  src/main/java/com/server/Dotori/model/member/service/role/RoleServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/role/RoleServiceImplTest.java
Labels: enhancement, code-review, Build Success

#105 회원탈퇴
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDeleteDto.java
  src/main/java/com/server/Dotori/model/member/service/MemberService.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
Labels: enhancement, code-review, Build Success

#106 hole 보완.
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
Labels: Build Success

#107 공지사항 컨트롤러
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/councillor/CouncillorBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/developer/DeveloperBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/member/MemberBoardController.java
Labels: Build Success

#110 음악 신청 컨트롤러
  src/main/java/com/server/Dotori/model/music/controller/admin/AdminMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
Labels: Build Success

#108 공지사항 조회 return type 변경
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/councillor/CouncillorBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/developer/DeveloperBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/member/MemberBoardController.java
Labels: Build Success

#114 자습신청 컨트롤러
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/admin/AdminSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/councillor/CouncillorSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/developer/DeveloperSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/member/MemberSelfStudyController.java
Labels: Build Success

#113 상벌점 컨트롤러
  src/main/java/com/server/Dotori/model/member/controller/point/PointController.java
  src/main/java/com/server/Dotori/model/member/controller/point/admin/AdminPointController.java
  src/main/java/com/server/Dotori/model/member/controller/point/developer/DeveloperPointController.java
  src/main/java/com/server/Dotori/model/member/dto/PointDto.java
Labels: Build Success

#112 Exception
  src/main/java/com/server/Dotori/exception/ExceptionAdvice.java
  src/main/java/com/server/Dotori/exception/ExceptionAdviceImpl.java
  src/main/java/com/server/Dotori/exception/basic_error/BasicErrorHandler.java
  src/main/java/com/server/Dotori/exception/basic_error/controller/BasicErrorController.java
  src/main/java/com/server/Dotori/exception/board/BoardExceptionHandler.java
  src/main/java/com/server/Dotori/exception/board/BoardExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/board/controller/BoardExceptionController.java
  src/main/java/com/server/Dotori/exception/board/exception/BoardEmptyException.java
  src/main/java/com/server/Dotori/exception/customError/BasicErrorController.java
  src/main/java/com/server/Dotori/exception/customError/CustomExceptionController.java
  src/main/java/com/server/Dotori/exception/customError/exception/CustomForbiddenException.java
  src/main/java/com/server/Dotori/exception/customError/exception/CustomNotFoundException.java
  src/main/java/com/server/Dotori/exception/customError/exception/CustomUnauthorizedException.java
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandler.java
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/music/controller/MusicExceptionController.java
  src/main/java/com/server/Dotori/exception/music/exception/MusicAlreadyException.java
  src/main/java/com/server/Dotori/exception/music/exception/MusicNotAppliedException.java
  src/main/java/com/server/Dotori/exception/music/exception/MusicNotFoundException.java
  src/main/java/com/server/Dotori/exception/selfstudy/SelfStudyExceptionHandler.java
  src/main/java/com/server/Dotori/exception/selfstudy/SelfStudyExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/selfstudy/controller/SelfStudyExceptionController.java
  src/main/java/com/server/Dotori/exception/selfstudy/exception/SelfStudyCantApplied.java
  src/main/java/com/server/Dotori/exception/selfstudy/exception/SelfStudyCantChange.java
  src/main/java/com/server/Dotori/exception/selfstudy/exception/SelfStudyNotFound.java
  src/main/java/com/server/Dotori/exception/selfstudy/exception/SelfStudyOverPersonal.java
  src/main/java/com/server/Dotori/exception/token/TokenExceptionHandler.java
  src/main/java/com/server/Dotori/exception/token/TokenExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/token/controller/TokenExceptionController.java
  src/main/java/com/server/Dotori/exception/token/exception/RefreshTokenFailException.java
  src/main/java/com/server/Dotori/exception/unknown_exception/UnknownExceptionHandler.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandler.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/user/controller/UserExceptionController.java
  src/main/java/com/server/Dotori/exception/user/exception/UserAuthenticationNumberNotMatchingException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserNotFoundByClassException.java
  src/main/java/com/server/Dotori/util/ExceptionResponseObjectUtil.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
Labels: code-review, Build Success

#117 현재 로그인된 유저 권한 조회 컨트롤러
  src/main/java/com/server/Dotori/model/member/controller/role/RoleController.java
Labels: Build Success

#116 학생 정보 변경 컨트롤러
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/admin/AdminStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/developer/DeveloperStuInfoController.java
Labels: Build Success

#118 권한별 컨트롤러 메소드 이름 변경
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/councillor/CouncillorBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/developer/DeveloperBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/member/MemberBoardController.java
  src/main/java/com/server/Dotori/model/member/controller/point/admin/AdminPointController.java
  src/main/java/com/server/Dotori/model/member/controller/point/developer/DeveloperPointController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/admin/AdminSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/councillor/CouncillorSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/developer/DeveloperSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/member/MemberSelfStudyController.java
  src/main/java/com/server/Dotori/model/music/controller/admin/AdminMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
Labels: Build Success

#121 오류 수정
  src/main/java/com/server/Dotori/exception/basic_error/BasicErrorHandler.java
  src/main/java/com/server/Dotori/exception/board/BoardExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/selfstudy/SelfStudyExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/token/TokenExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/unknown_exception/UnknownExceptionHandler.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandlerImpl.java
Labels: hotfix

#119 학생정보 변경 기능 예외처리 추가
  src/main/java/com/server/Dotori/model/member/repository/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
Labels: Build Success

#124 이름 유니크 속성 추가로 인한 테스트 실패 fix
  src/test/java/com/server/Dotori/model/member/service/point/PointServiceTest.java
Labels: bug, Build Success, hotfix

#125 Feature/exception message
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandler.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/user/controller/UserExceptionController.java
  src/main/java/com/server/Dotori/exception/user/exception/UserAuthenticationAnswerNotMatchingException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserAuthenticationNumberNotMatchingException.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
Labels: Build Success, hotfix

#126 질문 대답, 토큰 리프레시 Exception 처리 + Member username 컬럼 unique 속성 추가
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
Labels: bug, Build Success, correction

#127 board, music Exception
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
Labels: Build Success

#128 hotfix
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandler.java
Labels: Build Success, hotfix

#130 hotfix
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandler.java
Labels: Build Success, hotfix

#129 EmailServiceTest Disable처리
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
Labels: Build Success

#131 update music controller response status
  src/main/java/com/server/Dotori/model/music/controller/admin/AdminMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
Labels: Build Success

#132 basic exception
  src/main/java/com/server/Dotori/exception/basic_error/BasicErrorHandler.java
  src/main/java/com/server/Dotori/exception/basic_error/controller/BasicErrorController.java
Labels: Build Success

#133 SecurityConfig 권한별 Url 접속 에러 수정
  src/main/java/com/server/Dotori/security/SecurityConfig.java
Labels: bug, Build Success

#134 권한별 url 관련과 제 작업물에 대한 pr입니다.
  src/main/java/com/server/Dotori/exception/basic_error/controller/BasicErrorController.java
  src/main/java/com/server/Dotori/exception/board/BoardExceptionHandler.java
  src/main/java/com/server/Dotori/exception/dto/InvalidRequestDataHandler.java
  src/main/java/com/server/Dotori/exception/selfstudy/controller/SelfStudyExceptionController.java
  src/main/java/com/server/Dotori/exception/unknown_exception/UnknownExceptionHandler.java
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
  src/main/java/com/server/Dotori/response/ResponseService.java
  src/main/java/com/server/Dotori/response/result/CommonResult.java
  src/main/java/com/server/Dotori/security/SecurityConfig.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenFilter.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenFilterConfigurer.java
  src/test/java/com/server/Dotori/response/ResponseServiceTest.java
Labels: code-review, Build Success, hotfix

#135 컨트롤러 http status 변경
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/councillor/CouncillorBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/developer/DeveloperBoardController.java
  src/main/java/com/server/Dotori/model/member/controller/point/admin/AdminPointController.java
  src/main/java/com/server/Dotori/model/member/controller/point/developer/DeveloperPointController.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
Labels: Build Success

#136 공지사항, 음악신청 NotBlank 제약조건
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/councillor/CouncillorBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/developer/DeveloperBoardController.java
  src/main/java/com/server/Dotori/model/board/dto/BoardDto.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
  src/main/java/com/server/Dotori/model/music/dto/MusicApplicationDto.java
Labels: Build Success

#137 공지사항 title, content size 제약조건 추가
  src/main/java/com/server/Dotori/model/board/dto/BoardDto.java
Labels: Build Success

#139 mypage (main페이지) info controller mapping 수정
  src/main/java/com/server/Dotori/model/member/controller/mypage/MyPageController.java
Labels: Build Success

#138 Feature/user 회원 로직 제약조건 추가
  src/main/java/com/server/Dotori/model/member/controller/Email/EmailController.java
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/dto/AuthPasswordDto.java
  src/main/java/com/server/Dotori/model/member/dto/EmailDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberEmailKeyDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberLoginDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberPasswordDto.java
  src/main/java/com/server/Dotori/security/SecurityConfig.java
Labels: code-review, Build Success, correction
