Repository Team-Ampersand/Dotori-server, pull requests merged in 2021-08, with the labels that each got.

#48 [DELETE] comment function
  src/main/java/com/server/Dotori/model/board/Board.java
  src/main/java/com/server/Dotori/model/board/dto/BoardGetIdDto.java
  src/main/java/com/server/Dotori/model/board/repository/BoardRepository.java
  src/main/java/com/server/Dotori/model/board/repository/BoardRepositoryCustom.java
  src/main/java/com/server/Dotori/model/board/repository/BoardRepositoryImpl.java
  src/main/java/com/server/Dotori/model/comment/Comment.java
  src/main/java/com/server/Dotori/model/comment/controller/admin/AdminCommentController.java
  src/main/java/com/server/Dotori/model/comment/dto/CommentDto.java
  src/main/java/com/server/Dotori/model/comment/repository/CommentRepository.java
  src/main/java/com/server/Dotori/model/comment/service/CommentService.java
  src/main/java/com/server/Dotori/model/comment/service/CommentServiceImpl.java
  src/test/java/com/server/Dotori/model/comment/CommentTest.java
  src/test/java/com/server/Dotori/model/comment/service/CommentServiceTest.java
Labels: code-review

#51 [ADD] music Application
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/music/dto/MusicApplicationDto.java
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: code-review

#54 [ADD] getAllMusicList
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: code-review

#55 [ADD] delete this music
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: enhancement, code-review

#57 사감쌤이 버튼을 눌렀을 때 학생들의 음악신청 여부가 " 신청함 -> 신청가능 " 으로 update하는 service logic
  src/main/java/com/server/Dotori/model/music/repository/MusicRepository.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: enhancement, code-review, Build Success

#58 [FIX] q type error 해결
  build.gradle
Labels: Build Success

#59 [ADD] 매주 토요일 23시 59분 음악목록 초기화
  src/main/java/com/server/Dotori/DotoriApplication.java
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
  src/main/java/com/server/Dotori/util/UtilTest.java
  src/test/java/com/server/Dotori/model/music/schedule/MusicScheduleTest.java
Labels: enhancement, code-review, Build Success

#60 [UPDATE] displayname, 변수명
  src/test/java/com/server/Dotori/model/music/schedule/MusicScheduleTest.java
Labels: Build Success

#61 Develop -> Master
  build.gradle
  src/main/java/com/server/Dotori/DotoriApplication.java
  src/main/java/com/server/Dotori/config/querydsl/QuerydslConfiguration.java
  src/main/java/com/server/Dotori/model/board/Board.java
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/board/dto/BoardGetIdDto.java
  src/main/java/com/server/Dotori/model/board/service/BoardService.java
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
  src/main/java/com/server/Dotori/model/comment/Comment.java
  src/main/java/com/server/Dotori/model/comment/controller/admin/AdminCommentController.java
  src/main/java/com/server/Dotori/model/comment/repository/CommentRepository.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/controller/EmailController.java
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/dto/MemberEmailDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberEmailKeyDto.java
  src/main/java/com/server/Dotori/model/member/service/EmailSandService.java
  src/main/java/com/server/Dotori/model/member/service/EmailService.java
  src/main/java/com/server/Dotori/model/member/service/Impl/EmailSandServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/Impl/EmailServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/Impl/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/MemberService.java
  src/main/java/com/server/Dotori/model/music/dto/MusicApplicationDto.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepository.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/main/java/com/server/Dotori/security/SecurityConfig.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenFilter.java
  src/main/java/com/server/Dotori/util/UtilTest.java
  src/test/java/com/server/Dotori/model/board/service/BoardServiceTest.java
  src/test/java/com/server/Dotori/model/comment/CommentTest.java
  src/test/java/com/server/Dotori/model/music/schedule/MusicScheduleTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: Build Success

#63 [ADD] 자습신청
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/selfstudy/controller/SelfStudyController.java
  src/main/java/com/server/Dotori/model/selfstudy/service/SelfStudyService.java
  src/main/java/com/server/Dotori/model/selfstudy/service/SelfStudyServiceImpl.java
  src/test/java/com/server/Dotori/model/selfstudty/SelfStudyTest.java
  src/test/java/com/server/Dotori/model/selfstudy/service/SelfStudyServiceTest.java
Labels: enhancement, code-review, Build Success

#70 학생들의 자습신청 상태를 업데이트
  src/main/java/com/server/Dotori/model/selfstudy/controller/SelfStudyController.java
  src/main/java/com/server/Dotori/model/selfstudy/repository/SelfStudyRepositoryCustom.java
  src/main/java/com/server/Dotori/model/selfstudy/repository/SelfStudyRepositoryImpl.java
  src/main/java/com/server/Dotori/model/selfstudy/service/SelfStudyService.java
  src/main/java/com/server/Dotori/model/selfstudy/service/SelfStudyServiceImpl.java
  src/test/java/com/server/Dotori/model/selfstudy/service/SelfStudyServiceTest.java
Labels: enhancement, code-review, Build Success

#71 상벌점 부여
  src/main/java/com/server/Dotori/model/point/dto/PointDto.java
  src/main/java/com/server/Dotori/model/point/service/PointService.java
  src/main/java/com/server/Dotori/model/point/service/PointServiceImpl.java
  src/test/java/com/server/Dotori/model/point/service/PointServiceTest.java
Labels: enhancement, code-review, Build Success

#69 Feature/user
  src/main/java/com/server/Dotori/model/member/controller/EmailController.java
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/dto/EmailDto.java
  src/main/java/com/server/Dotori/model/member/repository/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/service/EmailSandService.java
  src/main/java/com/server/Dotori/model/member/service/EmailSendService.java
  src/main/java/com/server/Dotori/model/member/service/EmailService.java
  src/main/java/com/server/Dotori/model/member/service/Impl/EmailSendServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/Impl/EmailServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/Impl/MemberServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/EmailServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
Labels: code-review, Build Success
