Repository Team-Ampersand/Dotori-server, pull requests merged in 2022-03, with the labels that each got.

#294 매달마다 음악 목록을 삭제해주는 스케줄러 삭제
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
  src/test/java/com/server/Dotori/model/music/schedule/MusicScheduleTest.java
Labels: Correction, OK

#295 Develop
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
  src/test/java/com/server/Dotori/model/music/schedule/MusicScheduleTest.java
Labels: OK

#296 exception legacy 청산
  src/main/java/com/server/Dotori/exception/basic_error/BasicErrorHandler.java
  src/main/java/com/server/Dotori/exception/basic_error/controller/BasicErrorController.java
  src/main/java/com/server/Dotori/exception/massage/MassageExceptionHandler.java
  src/main/java/com/server/Dotori/exception/massage/MassageExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/massage/controller/MassageExceptionController.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageAlreadyException.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageCantRequestDateException.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageCantRequestTimeException.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageNoTheresException.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageNotAppliedStatusException.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageOverException.java
  src/main/java/com/server/Dotori/exception/member/exception/EmailHasNotBeenCertificateException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberAlreadyException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberAlreadyJoinThisNameException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberAlreadyJoinThisStunumException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberAuthenticationAnswerNotMatchingException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberAuthenticationKeyNotMatchingException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberNoInformationException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberNotFoundByClassException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberNotFoundException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberPasswordNotMatchingException.java
  src/main/java/com/server/Dotori/exception/member/exception/OverCertificateTimeException.java
  src/main/java/com/server/Dotori/exception/token/TokenExceptionHandler.java
  src/main/java/com/server/Dotori/exception/unknown_exception/UnknownExceptionHandler.java
  src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
  src/main/java/com/server/Dotori/new_exception/DotoriException.java
  src/main/java/com/server/Dotori/new_exception/ErrorCode.java
  src/main/java/com/server/Dotori/new_exception/ErrorResponse.java
  src/main/java/com/server/Dotori/new_exception/handler/DotoriExceptionHandler.java
  src/main/java/com/server/Dotori/new_exception/handler/UnknownExceptionHandler.java
  src/main/java/com/server/Dotori/security/exception/ExceptionHandlerFilter.java
  src/test/java/com/server/Dotori/model/member/service/massage/MassageServiceTest.java
Labels: Correction, Migration, OK

#297 Board feature 변경된 exception으로 변경
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
Labels: Documentation, Correction, OK

#298 music feature 변경된 exception으로 변경
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: Documentation, Correction, OK

#300 stu-info feature 변경된 exception으로 변경
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
Labels: Documentation, Correction, OK

#299 self-study feature 변경된 exception으로 변경
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
Labels: Documentation, Correction, OK

#302 Rule Exception 변경
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
  src/main/java/com/server/Dotori/security/authentication/MyMemberDetails.java
  src/test/java/com/server/Dotori/model/rule/service/RuleServiceTest.java
Labels: Correction, TODO, OK

#303 @Valid를 통한 MethodArgumentNotValidException 핸들링
  src/main/java/com/server/Dotori/exception/dto/InvalidRequestDataHandler.java
  src/main/java/com/server/Dotori/new_exception/ErrorResponse.java
  src/main/java/com/server/Dotori/new_exception/handler/DotoriExceptionHandler.java
Labels: Correction, OK

#304 refresh 구조 변경으로 로그인유지
  src/main/java/com/server/Dotori/model/member/controller/RefreshTokenController.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenService.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/new_exception/ErrorCode.java
  src/main/java/com/server/Dotori/security/SecurityConfig.java
  src/main/java/com/server/Dotori/security/exception/ExceptionHandlerFilter.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenProvider.java
Labels: Documentation, Code-Review, Correction, OK

#305 board count 로직 작성
  src/main/java/com/server/Dotori/model/board/controller/common/CommonBoardController.java
  src/main/java/com/server/Dotori/model/board/service/BoardService.java
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
  src/main/java/com/server/Dotori/security/SecurityConfig.java
  src/test/java/com/server/Dotori/model/board/service/BoardServiceTest.java
Labels: Documentation, Enhancement, Code-Review, OK

#307 규정위반 조회에서 대분류 조회도 할 수 있도록 변경
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/rule/dto/FindStusDto.java
  src/main/java/com/server/Dotori/model/rule/enumType/Rule.java
Labels: Code-Review, Correction, OK

#306 새로 추가된 인원들 dev 환경에서 미리 회원가입 시켜놓는 코드 추가
  src/main/java/com/server/Dotori/dev_config/GenerateMember.java
Labels: Correction, OK

#309 Hotfix 테스트 오류나던 부분 fix
  src/main/java/com/server/Dotori/domain/main_page/dto/GetProfileDto.java
  src/main/java/com/server/Dotori/domain/main_page/service/Impl/MainPageServiceImpl.java
  src/main/java/com/server/Dotori/domain/main_page/service/MainPageService.java
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/server/Dotori/domain/member/service/impl/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/domain/point/dto/GetAboutPointDto.java
  src/main/java/com/server/Dotori/domain/point/service/Impl/PointServiceImpl.java
  src/main/java/com/server/Dotori/domain/point/service/PointService.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepository.java
  src/main/java/com/server/Dotori/domain/self_study/schedule/SelfStudySchedule.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/global/config/exception/MessageConfiguration.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/Dotori/domain/main_page/main_page/service/MainPageServiceTest.java
  src/test/java/com/server/Dotori/domain/massage/schedule/MassageScheduleTest.java
  src/test/java/com/server/Dotori/domain/massage/service/MassageServiceTest.java
  src/test/java/com/server/Dotori/domain/music/schedule/MusicScheduleTest.java
  src/test/java/com/server/Dotori/domain/point/PointServiceTest.java
  src/test/java/com/server/Dotori/domain/self_study/schedule/SelfStudyScheduleTest.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyServiceTest.java
Labels: Hotfix, Correction, Migration

#310 반환되는 http status code가 exception 변경 과정에서 변경되어서 client에서 오류발생
  src/main/java/com/server/Dotori/global/exception/ErrorCode.java
Labels: Bug, Hotfix, Correction

#311 Rule 대분류 이름 변경
  src/main/java/com/server/Dotori/domain/rule/enumType/Rule.java
Labels: Correction, OK

#312 자습신청 한 학생 자습신청 한 순서대로 조회하는 기능
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/self_study/controller/admin/AdminSelfStudyController.java
  src/main/java/com/server/Dotori/domain/self_study/controller/councillor/CouncillorSelfStudyController.java
  src/main/java/com/server/Dotori/domain/self_study/controller/developer/DeveloperSelfStudyController.java
  src/main/java/com/server/Dotori/domain/self_study/controller/member/MemberSelfStudyController.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepository.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryCustom.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/SelfStudyService.java
  src/main/java/com/server/Dotori/global/config/dev/GenerateMember.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyServiceTest.java
Labels: Documentation, Enhancement, Code-Review, Requirements

#313 얼마전에 바뀌였던 token을 refresh 하는 로직을 변경 했습니다.
  src/main/java/com/server/Dotori/domain/member/controller/RefreshTokenController.java
  src/main/java/com/server/Dotori/domain/member/dto/RefreshTokenDto.java
  src/main/java/com/server/Dotori/domain/member/service/RefreshTokenService.java
  src/main/java/com/server/Dotori/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/server/Dotori/domain/member/service/impl/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/global/security/jwt/JwtTokenProvider.java
Labels: Correction, OK

#315 Member 부분 ErrorCode Http Method fix
  src/main/java/com/server/Dotori/global/exception/ErrorCode.java
Labels: Hotfix, Correction
