Repository Team-Ampersand/Dotori-server, pull requests merged in 2022-05, with the labels that each got.

#361 hotfix develop
  src/main/java/com/server/Dotori/domain/board/dto/BoardGetDto.java
  src/main/java/com/server/Dotori/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Dotori/domain/main_page/dto/BoardAlarmDto.java
  src/main/java/com/server/Dotori/domain/main_page/service/Impl/BoardAlarmServiceImpl.java
  src/main/java/com/server/Dotori/domain/massage/controller/councillor/CouncillorMassageController.java
  src/main/java/com/server/Dotori/domain/massage/controller/developer/DeveloperMassageController.java
  src/main/java/com/server/Dotori/domain/massage/controller/member/MemberMassageController.java
  src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
  src/main/java/com/server/Dotori/domain/massage/service/MassageService.java
  src/main/java/com/server/Dotori/domain/member/Member.java
  src/main/java/com/server/Dotori/domain/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/domain/member/enumType/MassageStatus.java
  src/main/java/com/server/Dotori/domain/member/enumType/MusicStatus.java
  src/main/java/com/server/Dotori/domain/member/enumType/SelfStudyStatus.java
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/domain/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/music/service/Impl/MusicServiceImpl.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/domain/stu_info/dto/StudentInfoDto.java
  src/main/java/com/server/Dotori/domain/stu_info/service/Impl/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/global/config/dev/GenerateMember.java
  src/main/java/com/server/Dotori/global/exception/ErrorCode.java
  src/test/java/com/server/Dotori/domain/main_page/board_alarm/service/BoardAlarmServiceTest.java
  src/test/java/com/server/Dotori/domain/massage/schedule/MassageStatusScheduleTest.java
  src/test/java/com/server/Dotori/domain/massage/service/MassageStatusServiceTest.java
  src/test/java/com/server/Dotori/domain/member/MemberTest.java
  src/test/java/com/server/Dotori/domain/member/exception/MemberExceptionTest.java
  src/test/java/com/server/Dotori/domain/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/domain/music/schedule/MusicStatusScheduleTest.java
  src/test/java/com/server/Dotori/domain/music/service/MusicStatusServiceTest.java
  src/test/java/com/server/Dotori/domain/point/PointServiceTest.java
  src/test/java/com/server/Dotori/domain/self_study/schedule/SelfStudyStatusScheduleTest.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyStatusServiceTest.java
  src/test/java/com/server/Dotori/domain/stu_info/service/StuInfoServiceTest.java
Labels: Hotfix

#362 로그 변경
  src/main/java/com/server/Dotori/global/config/interceptor/Interceptor.java
  src/main/java/com/server/Dotori/global/config/web/WebConfig.java
  src/main/java/com/server/Dotori/global/exception/DotoriException.java
  src/main/java/com/server/Dotori/global/exception/handler/DotoriExceptionHandler.java
  src/main/java/com/server/Dotori/global/security/SecurityConfig.java
  src/main/java/com/server/Dotori/global/util/CurrentMemberUtil.java
  src/test/java/com/server/Dotori/domain/rule/service/RuleServiceTest.java
Labels: Enhancement, Code-Review, OK

#366 담당 Controller, Service 레이어 주석, 메소드명 개편
  src/main/java/com/server/Dotori/domain/member/controller/MemberController.java
  src/main/java/com/server/Dotori/domain/member/controller/RefreshTokenController.java
  src/main/java/com/server/Dotori/domain/member/controller/SignController.java
  src/main/java/com/server/Dotori/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/server/Dotori/domain/rule/controller/admin/AdminRuleController.java
  src/main/java/com/server/Dotori/domain/rule/controller/councillor/CouncillorRuleController.java
  src/main/java/com/server/Dotori/domain/rule/controller/developer/DeveloperRuleController.java
  src/main/java/com/server/Dotori/domain/rule/controller/member/MemberRuleController.java
  src/main/java/com/server/Dotori/domain/rule/dto/ViolationOfTheRuleResponseDto.java
  src/main/java/com/server/Dotori/domain/rule/service/Impl/RuleServiceImpl.java
  src/main/java/com/server/Dotori/domain/rule/service/RuleService.java
Labels: Documentation, Correction, OK

#368 logback 적용 ( 로그 파일로 저장 )
  backup/error/.gitkeep
  backup/info/.gitkeep
  backup/warn/.gitkeep
  logs/error/.gitkeep
  logs/info/.gitkeep
  logs/warn/.gitkeep
  src/main/resources/logback.xml
Labels: Enhancement, Code-Review, OK

#367 자습신청 feature JPA 비관적 Lock 적용
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/self_study/SelfStudyCount.java
  src/main/java/com/server/Dotori/domain/self_study/dev/SelfStudyCountConfig.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyCountRepository.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryCustom.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyStatusServiceTest.java
Labels: Correction, OK

#359 음악신청 서비스 로직 코드 더 깔끔하게
  src/main/java/com/server/Dotori/domain/member/Member.java
  src/main/java/com/server/Dotori/domain/music/service/Impl/MusicServiceImpl.java
  src/main/java/com/server/Dotori/domain/stu_info/service/Impl/StuInfoServiceImpl.java
  src/test/java/com/server/Dotori/domain/music/service/MusicStatusServiceTest.java
Labels: Documentation, Correction, OK
