Repository Team-Ampersand/Dotori-server, pull requests merged in 2022-04, with the labels that each got.

#316 Massage SelfStudy 트랜잭션 처리
  src/main/java/com/server/Dotori/domain/massage/Massage.java
  src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
  src/main/java/com/server/Dotori/domain/self_study/SelfStudy.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
Labels: Code-Review, OK

#318 공지사항 전체조회 로직 수정
  src/main/java/com/server/Dotori/domain/board/dto/BoardGetDto.java
  src/main/java/com/server/Dotori/domain/board/repository/BoardRepository.java
  src/main/java/com/server/Dotori/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/server/Dotori/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/board/service/Impl/BoardServiceImpl.java
Labels: Correction, OK

#319 [FIX] 공지사항 전체조회 쿼리 페이징 fix
  src/main/java/com/server/Dotori/domain/board/repository/BoardRepositoryImpl.java
Labels: Correction

#320 규정위반 부여 여러명 가능하도록 변경
  src/main/java/com/server/Dotori/domain/rule/dto/RuleGrantDto.java
  src/main/java/com/server/Dotori/domain/rule/service/Impl/RuleServiceImpl.java
  src/test/java/com/server/Dotori/domain/rule/service/RuleServiceTest.java
Labels: Correction, OK

#322 성별 관련 업데이트
  src/main/java/com/server/Dotori/domain/main_page/dto/GetProfileDto.java
  src/main/java/com/server/Dotori/domain/main_page/service/Impl/MainPageServiceImpl.java
  src/main/java/com/server/Dotori/domain/member/Member.java
  src/main/java/com/server/Dotori/domain/member/controller/MemberController.java
  src/main/java/com/server/Dotori/domain/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/domain/member/dto/SetGenderDto.java
  src/main/java/com/server/Dotori/domain/member/enumType/Gender.java
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/member/service/MemberService.java
  src/main/java/com/server/Dotori/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/server/Dotori/global/config/dev/GenerateMember.java
  src/main/java/com/server/Dotori/global/security/SecurityConfig.java
Labels: Enhancement, Code-Review, Correction, TODO, Requirements

#321 테스트 커버리지 관리를 위한 Jacoco 추가
  build.gradle
Labels: Enhancement, OK

#323 성별 에러나는 테스트 코드 수정 + 잘못 된 코드 수정
  src/main/java/com/server/Dotori/domain/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/server/Dotori/global/config/dev/GenerateMember.java
  src/test/java/com/server/Dotori/domain/board/service/BoardServiceTest.java
  src/test/java/com/server/Dotori/domain/main_page/main_page/service/MainPageServiceTest.java
  src/test/java/com/server/Dotori/domain/main_page/role/service/RoleServiceImplTest.java
  src/test/java/com/server/Dotori/domain/massage/service/MassageServiceTest.java
  src/test/java/com/server/Dotori/domain/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/domain/music/service/MusicServiceTest.java
  src/test/java/com/server/Dotori/domain/point/PointServiceTest.java
  src/test/java/com/server/Dotori/domain/rule/service/RuleServiceTest.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/domain/stu_info/service/StuInfoServiceTest.java
  src/test/java/com/server/Dotori/global/security/SecurityTest.java
  src/test/java/com/server/Dotori/global/util/CurrentMemberUtilTest.java
Labels: Correction, OK

#325 메인페이지 배너 새로운 공지사항 정보 API
  src/main/java/com/server/Dotori/domain/board/controller/common/CommonBoardController.java
  src/main/java/com/server/Dotori/domain/board/repository/BoardRepository.java
  src/main/java/com/server/Dotori/domain/board/service/BoardService.java
  src/main/java/com/server/Dotori/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Dotori/domain/main_page/controller/BoardAlarmController.java
  src/main/java/com/server/Dotori/domain/main_page/dto/BoardAlarmDto.java
  src/main/java/com/server/Dotori/domain/main_page/service/BoardAlarmService.java
  src/main/java/com/server/Dotori/domain/main_page/service/Impl/BoardAlarmServiceImpl.java
  src/main/java/com/server/Dotori/global/security/SecurityConfig.java
  src/test/java/com/server/Dotori/domain/board/service/BoardServiceTest.java
  src/test/java/com/server/Dotori/domain/main_page/board_alarm/service/BoardAlarmServiceTest.java
Labels: Code-Review, Correction, OK

#326 테스트 커버리지 제외목록 추가
  build.gradle
Labels: Correction, OK

#327 개발서버, 운영서버 SecurityConfig 분리
  src/main/java/com/server/Dotori/global/security/SecurityConfig.java
Labels: Hotfix

#329 안마의자 신청 상태반환 api에 만료 기간일도 추가
  src/main/java/com/server/Dotori/domain/massage/controller/admin/AdminMassageController.java
  src/main/java/com/server/Dotori/domain/massage/controller/councillor/CouncillorMassageController.java
  src/main/java/com/server/Dotori/domain/massage/controller/developer/DeveloperMassageController.java
  src/main/java/com/server/Dotori/domain/massage/controller/member/MemberMassageController.java
  src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
  src/main/java/com/server/Dotori/domain/massage/service/MassageService.java
  src/test/java/com/server/Dotori/domain/massage/service/MassageServiceTest.java
Labels: Correction, OK

#330 학생정보 성별 변경, 자습신청 목록 성별 추가
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/self_study/dto/SelfStudyStudentsDto.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/domain/stu_info/controller/admin/AdminStuInfoController.java
  src/main/java/com/server/Dotori/domain/stu_info/controller/councillor/CouncillorStuInfoController.java
  src/main/java/com/server/Dotori/domain/stu_info/controller/developer/DeveloperStuInfoController.java
  src/main/java/com/server/Dotori/domain/stu_info/dto/GenderUpdateDto.java
  src/main/java/com/server/Dotori/domain/stu_info/dto/StudentInfoDto.java
  src/main/java/com/server/Dotori/domain/stu_info/service/Impl/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/domain/stu_info/service/StuInfoService.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/domain/stu_info/service/StuInfoServiceTest.java
Labels: Enhancement, Code-Review, Correction, OK

#331 안마의자 상태 반환 api hotfix
  src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
Labels: Hotfix, OK

#332 SignIn 에서 gender 반환 + logout @Transactional 추가
  src/main/java/com/server/Dotori/domain/member/controller/SignController.java
  src/main/java/com/server/Dotori/domain/member/dto/SignInResponseDto.java
  src/main/java/com/server/Dotori/domain/member/service/MemberService.java
  src/main/java/com/server/Dotori/domain/member/service/impl/MemberServiceImpl.java
  src/test/java/com/server/Dotori/domain/member/service/MemberServiceTest.java
Labels: Enhancement, Code-Review, Correction, OK

#333 board 5000 자 까지 수용할 수 있게 변경 + member Gender email로 변경 할 수 있게 변경
  src/main/java/com/server/Dotori/domain/board/Board.java
  src/main/java/com/server/Dotori/domain/board/dto/BoardDto.java
  src/main/java/com/server/Dotori/domain/member/dto/SetGenderDto.java
  src/main/java/com/server/Dotori/domain/member/service/impl/MemberServiceImpl.java
Labels: Correction, OK

#334 조회한 공지사항이 비어있을 때 예외처리
  src/main/java/com/server/Dotori/domain/main_page/service/Impl/BoardAlarmServiceImpl.java
Labels: Hotfix

#336 massage expiredDate 관련 코드삭제
  src/main/java/com/server/Dotori/domain/massage/controller/admin/AdminMassageController.java
  src/main/java/com/server/Dotori/domain/massage/controller/councillor/CouncillorMassageController.java
  src/main/java/com/server/Dotori/domain/massage/controller/developer/DeveloperMassageController.java
  src/main/java/com/server/Dotori/domain/massage/controller/member/MemberMassageController.java
  src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
  src/main/java/com/server/Dotori/domain/member/Member.java
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryImpl.java
Labels: Documentation, Correction, OK

#338 SelfStudy feature 보완 (SelfStudy 서비스 로직 테스트 커버리지 100% 달성)
  build.gradle
  src/main/java/com/server/Dotori/domain/self_study/controller/admin/AdminSelfStudyController.java
  src/main/java/com/server/Dotori/domain/self_study/controller/councillor/CouncillorSelfStudyController.java
  src/main/java/com/server/Dotori/domain/self_study/controller/developer/DeveloperSelfStudyController.java
  src/main/java/com/server/Dotori/domain/self_study/controller/member/MemberSelfStudyController.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryCustom.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/SelfStudyService.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyServiceTest.java
Labels: Documentation, Code-Review, Correction, OK

#337 board page 개수 6개로 변경
  src/main/java/com/server/Dotori/domain/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/domain/board/controller/councillor/CouncillorBoardController.java
  src/main/java/com/server/Dotori/domain/board/controller/developer/DeveloperBoardController.java
  src/main/java/com/server/Dotori/domain/board/controller/member/MemberBoardController.java
  src/main/java/com/server/Dotori/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Dotori/domain/board/service/Impl/S3ServiceImpl.java
  src/main/java/com/server/Dotori/domain/board/service/S3Service.java
  src/test/java/com/server/Dotori/domain/board/service/BoardServiceTest.java
Labels: Correction, OK

#339 Music Feature 보완
  src/main/java/com/server/Dotori/domain/music/controller/admin/AdminMusicController.java
  src/main/java/com/server/Dotori/domain/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/domain/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/domain/music/controller/member/MemberMusicController.java
  src/main/java/com/server/Dotori/domain/music/service/Impl/MusicServiceImpl.java
  src/main/java/com/server/Dotori/domain/music/service/MusicService.java
  src/test/java/com/server/Dotori/domain/music/service/MusicServiceTest.java
Labels: Documentation, Code-Review, Correction, OK

#340 메인페이지 , 학생정보 서비스 로직 테스트 커버리지
  src/main/java/com/server/Dotori/domain/stu_info/service/Impl/StuInfoServiceImpl.java
  src/test/java/com/server/Dotori/domain/main_page/board_alarm/service/BoardAlarmServiceTest.java
  src/test/java/com/server/Dotori/domain/stu_info/service/StuInfoServiceTest.java
Labels: Documentation, Correction, OK

#341 massage enum type중 impossible 제거
  src/main/java/com/server/Dotori/domain/member/enumType/Massage.java
Labels: Hotfix

#343 Member 테스트 커버리지 100%
  src/main/java/com/server/Dotori/domain/member/dto/ChangePasswordEmailCheckDto.java
  src/main/java/com/server/Dotori/domain/member/dto/EmailDto.java
  src/main/java/com/server/Dotori/domain/member/dto/RefreshTokenDto.java
  src/main/java/com/server/Dotori/domain/member/dto/SetGenderDto.java
  src/main/java/com/server/Dotori/domain/member/dto/SignUpEmailCheckDto.java
  src/test/java/com/server/Dotori/domain/member/MemberTest.java
  src/test/java/com/server/Dotori/domain/member/exception/MemberExceptionTest.java
  src/test/java/com/server/Dotori/domain/member/exception/RefreshTokenExceptionTest.java
  src/test/java/com/server/Dotori/domain/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/domain/member/service/RefreshTokenServiceTest.java
Labels: Correction, OK

#345 Update 기본 생성자 추가
  src/main/java/com/server/Dotori/domain/member/dto/ChangePasswordEmailCheckDto.java
  src/main/java/com/server/Dotori/domain/member/dto/EmailDto.java
  src/main/java/com/server/Dotori/domain/member/dto/RefreshTokenDto.java
  src/main/java/com/server/Dotori/domain/member/dto/SetGenderDto.java
  src/main/java/com/server/Dotori/domain/member/dto/SignUpEmailCheckDto.java
Labels: Hotfix

#347 Multi thread 환경에서 자습신청을 했을 때 51명이 신청되는 동시성 이슈 해결
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepository.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
Labels: Documentation, Code-Review, Correction, OK

#348 rule enum 타입 분류 세분화
  src/main/java/com/server/Dotori/domain/rule/enumType/Rule.java
Labels: Correction, OK

#349 MultiThread 동시성 문제 설계상 비관적 Lock이 적용되지 않아 synchronized로 변경
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepository.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyServiceTest.java
Labels: Correction, OK

#350 안마의자 신청 서비스로직 synchronized 추가 (추후 개선 필요)
  src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
Labels: Correction

#352 hotfix rule 목록 이름 변경
  src/main/java/com/server/Dotori/domain/rule/enumType/Rule.java
Labels: Hotfix, OK

#354 Hotifx
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryCustom.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/SelfStudyService.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyServiceTest.java
Labels: Hotfix

#356 member 엔티티 부분 status들 네이밍 변경
  src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
  src/main/java/com/server/Dotori/domain/member/Member.java
  src/main/java/com/server/Dotori/domain/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/domain/member/enumType/MassageStatus.java
  src/main/java/com/server/Dotori/domain/member/enumType/MusicStatus.java
  src/main/java/com/server/Dotori/domain/member/enumType/SelfStudyStatus.java
  src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/music/service/Impl/MusicServiceImpl.java
  src/main/java/com/server/Dotori/domain/self_study/repository/SelfStudyRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/domain/stu_info/dto/StudentInfoDto.java
  src/main/java/com/server/Dotori/global/config/dev/GenerateMember.java
  src/test/java/com/server/Dotori/domain/massage/schedule/MassageStatusScheduleTest.java
  src/test/java/com/server/Dotori/domain/massage/service/MassageStatusServiceTest.java
  src/test/java/com/server/Dotori/domain/member/MemberTest.java
  src/test/java/com/server/Dotori/domain/member/exception/MemberExceptionTest.java
  src/test/java/com/server/Dotori/domain/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/domain/music/schedule/MusicStatusScheduleTest.java
  src/test/java/com/server/Dotori/domain/music/service/MusicStatusServiceTest.java
  src/test/java/com/server/Dotori/domain/point/PointServiceTest.java
  src/test/java/com/server/Dotori/domain/self_study/schedule/SelfStudyStatusScheduleTest.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyStatusServiceTest.java
Labels: Correction, OK

#357 상수와 혼용하여 오해할 수 있어 static import 제거
  src/main/java/com/server/Dotori/domain/board/dto/BoardGetDto.java
  src/main/java/com/server/Dotori/domain/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/server/Dotori/domain/main_page/dto/BoardAlarmDto.java
  src/main/java/com/server/Dotori/domain/main_page/service/Impl/BoardAlarmServiceImpl.java
  src/main/java/com/server/Dotori/domain/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/domain/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/domain/music/service/Impl/MusicServiceImpl.java
  src/main/java/com/server/Dotori/domain/self_study/service/Impl/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/domain/stu_info/service/Impl/StuInfoServiceImpl.java
  src/test/java/com/server/Dotori/domain/main_page/board_alarm/service/BoardAlarmServiceTest.java
  src/test/java/com/server/Dotori/domain/music/service/MusicStatusServiceTest.java
  src/test/java/com/server/Dotori/domain/self_study/service/SelfStudyStatusServiceTest.java
  src/test/java/com/server/Dotori/domain/stu_info/service/StuInfoServiceTest.java
Labels: Correction

#358 안마의자 전체적인 리팩토링 및 안마의자 신청 취소 로직 부분변경
  src/main/java/com/server/Dotori/domain/massage/controller/councillor/CouncillorMassageController.java
  src/main/java/com/server/Dotori/domain/massage/controller/developer/DeveloperMassageController.java
  src/main/java/com/server/Dotori/domain/massage/controller/member/MemberMassageController.java
  src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
  src/main/java/com/server/Dotori/domain/massage/service/MassageService.java
  src/main/java/com/server/Dotori/global/exception/ErrorCode.java
  src/test/java/com/server/Dotori/domain/massage/service/MassageStatusServiceTest.java
Labels: Documentation, Code-Review, Correction, OK
