Repository Team-Ampersand/Dotori-server, pull requests merged in 2022-01, with the labels that each got.

#232 Exception 추가, Entity Modelling
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandler.java
  src/main/java/com/server/Dotori/exception/music/MusicExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/music/controller/MusicExceptionController.java
  src/main/java/com/server/Dotori/exception/music/exception/MusicNotRequestOnThatDateException.java
  src/main/java/com/server/Dotori/model/board/Board.java
  src/main/java/com/server/Dotori/model/board/Image.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
Labels: Build Success

#231 해당 날짜에 신청된 기상음악 조회
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/admin/AdminStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/councillor/CouncillorStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/developer/DeveloperStuInfoController.java
  src/main/java/com/server/Dotori/model/music/controller/admin/AdminMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
  src/main/java/com/server/Dotori/model/music/dto/DateMusicDto.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryCustom.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/schedule/MusicSchedule.java
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/music/schedule/MusicScheduleTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: OK

#233 공지사항 사진 첨부
  build.gradle
  src/main/java/com/server/Dotori/config/aws/AwsS3Config.java
  src/main/java/com/server/Dotori/model/board/Board.java
  src/main/java/com/server/Dotori/model/board/Image.java
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/councillor/CouncillorBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/developer/DeveloperBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/member/MemberBoardController.java
  src/main/java/com/server/Dotori/model/board/dto/BoardDto.java
  src/main/java/com/server/Dotori/model/board/dto/BoardGetIdDto.java
  src/main/java/com/server/Dotori/model/board/service/BoardService.java
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
  src/main/java/com/server/Dotori/model/board/service/S3Service.java
  src/test/java/com/server/Dotori/model/board/service/BoardServiceTest.java
Labels: Enhancement, Code-Review, OK, Solve-Together

#243 music date 관련 @TeMlN님이 추가해주신 Exception으로 변경
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
Labels: OK

#244 jwt 개선 및 변수 user -> member 로 이름 변경
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/admin/AdminStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/councillor/CouncillorStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/developer/DeveloperStuInfoController.java
  src/main/java/com/server/Dotori/model/member/dto/GetAboutPointDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberNameUpdateDto.java
  src/main/java/com/server/Dotori/model/member/dto/SelfStudyStudentsDto.java
  src/main/java/com/server/Dotori/model/member/dto/StudentInfoDto.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/role/RoleServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoService.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/model/music/dto/MusicResDto.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/main/java/com/server/Dotori/security/authentication/MyMemberDetails.java
  src/main/java/com/server/Dotori/security/jwt/JwtTokenProvider.java
  src/main/java/com/server/Dotori/util/CurrentMemberUtil.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
Labels: Bug, Code-Review, Correction, TODO, OK

#245 Test 오류나는 부분 Hotfix
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/test/java/com/server/Dotori/model/board/service/BoardServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/point/PointServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/role/RoleServiceImplTest.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
  src/test/java/com/server/Dotori/util/CurrentMemberUtilTest.java
Labels: Bug, Hotfix, OK

#246 서비스로직 currentUser 변수명 currentMember로 변경
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/councillor/CouncillorBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/developer/DeveloperBoardController.java
  src/main/java/com/server/Dotori/model/board/service/BoardServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
Labels: Bug, Documentation, Correction, OK

#247 stdNum -> stuNum
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/dto/SelfStudyStudentsDto.java
  src/main/java/com/server/Dotori/model/member/dto/StudentInfoDto.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepository.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/test/java/com/server/Dotori/model/board/service/BoardServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/point/PointServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/role/RoleServiceImplTest.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
  src/test/java/com/server/Dotori/security/SecurityTest.java
  src/test/java/com/server/Dotori/util/CurrentMemberUtilTest.java
Labels: Bug, Correction, OK

#248 Exception 네이밍 변경 및 테스트케이스 컬럼명 변경
  src/main/java/com/server/Dotori/exception/member/MemberExceptionHandler.java
  src/main/java/com/server/Dotori/exception/member/MemberExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/member/controller/MemberExceptionController.java
  src/main/java/com/server/Dotori/exception/member/exception/EmailHasNotBeenCertificateException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberAlreadyException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberAlreadyJoinThisNameException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberAlreadyJoinThisStunumException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberAuthenticationAnswerNotMatchingException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberAuthenticationKeyNotMatchingException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberNoInformationException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberNotFoundByClassException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberNotFoundException.java
  src/main/java/com/server/Dotori/exception/member/exception/MemberPasswordNotMatchingException.java
  src/main/java/com/server/Dotori/exception/member/exception/OverCertificateTimeException.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandler.java
  src/main/java/com/server/Dotori/exception/user/UserExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/user/controller/UserExceptionController.java
  src/main/java/com/server/Dotori/exception/user/exception/UserAlreadyException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserAlreadyJoinThisNameException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserAlreadyJoinThisStunumException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserAuthenticationAnswerNotMatchingException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserAuthenticationKeyNotMatchingException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserNoInformationException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserNotFoundByClassException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserNotFoundException.java
  src/main/java/com/server/Dotori/exception/user/exception/UserPasswordNotMatchingException.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/RefreshTokenServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/point/PointServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/main/java/com/server/Dotori/security/authentication/MyMemberDetails.java
  src/main/java/com/server/Dotori/util/CurrentMemberUtil.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/Dotori/model/member/MemberTest.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
Labels: Correction, OK

#249 아직 변경되지 않은 Username -> MemberName 으로 변경 및 stdNum 을 stuNum 으로 통일
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/admin/AdminStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/councillor/CouncillorStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/developer/DeveloperStuInfoController.java
  src/main/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceImpl.java
  src/test/java/com/server/Dotori/model/member/MemberTest.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
  src/test/java/com/server/Dotori/security/SecurityTest.java
Labels: Code-Review, Correction, OK

#250 API 테스트하며 수정사항 반영
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/councillor/CouncillorBoardController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/admin/AdminStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/councillor/CouncillorStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/developer/DeveloperStuInfoController.java
Labels: OK

#251 학생 규정위반을 했을때 기록 하는 기능 추가
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepository.java
  src/main/java/com/server/Dotori/model/rule/RuleViolation.java
  src/main/java/com/server/Dotori/model/rule/controller/RuleController.java
  src/main/java/com/server/Dotori/model/rule/dto/RuleGrantDto.java
  src/main/java/com/server/Dotori/model/rule/enumType/Rule.java
  src/main/java/com/server/Dotori/model/rule/repository/RuleRepository.java
  src/main/java/com/server/Dotori/model/rule/service/RuleService.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
  src/test/java/com/server/Dotori/model/rule/service/RuleServiceTest.java
Labels: Enhancement, Code-Review, TODO, OK

#252 자신이 신청한 기상음악을 삭제할 수 있다. (member 권한)
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
  src/main/java/com/server/Dotori/model/music/dto/MusicResDto.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
Labels: Enhancement, Code-Review, Requirements, OK

#253 개발 편의를 위한 WAS 띄울 때 회원 생성 후 token logging
  src/main/java/com/server/Dotori/dev_config/GenerateMember.java
Labels: Enhancement, Code-Review, OK

#254 음악 날짜조회 cross join 명시적 join으로 변경하여 성능 개선
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
Labels: Correction, Optimization, OK

#256 오늘 신청한 기상음악 조회 API 삭제, 기상음악 전체조회와 날짜로 기상음악 조회 API 통합
  src/main/java/com/server/Dotori/model/music/controller/admin/AdminMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/councillor/CouncillorMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/developer/DeveloperMusicController.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
  src/main/java/com/server/Dotori/model/music/dto/DateMusicDto.java
  src/main/java/com/server/Dotori/model/music/repository/MusicRepositoryImpl.java
  src/main/java/com/server/Dotori/model/music/service/MusicService.java
  src/main/java/com/server/Dotori/model/music/service/MusicServiceImpl.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
Labels: Documentation, Code-Review, Correction, Optimization, OK

#255 기숙사 규정을 어긴 학생의 이력을 조회하는 기능 추가
  src/main/java/com/server/Dotori/model/rule/RuleViolation.java
  src/main/java/com/server/Dotori/model/rule/controller/RuleController.java
  src/main/java/com/server/Dotori/model/rule/dto/FindRulesAndDatesDto.java
  src/main/java/com/server/Dotori/model/rule/dto/RulesCntAndDatesDto.java
  src/main/java/com/server/Dotori/model/rule/enumType/Rule.java
  src/main/java/com/server/Dotori/model/rule/repository/RuleRepository.java
  src/main/java/com/server/Dotori/model/rule/repository/RuleRepositoryCustom.java
  src/main/java/com/server/Dotori/model/rule/repository/RuleRepositoryCustomImpl.java
  src/main/java/com/server/Dotori/model/rule/service/RuleService.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
  src/test/java/com/server/Dotori/model/rule/service/RuleServiceTest.java
Labels: Documentation, Code-Review, TODO, OK

#257 안마의자 신청 기능 추가
  src/main/java/com/server/Dotori/model/massage/Massage.java
  src/main/java/com/server/Dotori/model/massage/controller/admin/AdminMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/councillor/CouncillorMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/develop/DevelopMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/member/MemberMassageController.java
  src/main/java/com/server/Dotori/model/massage/repository/MassageRepository.java
  src/main/java/com/server/Dotori/model/massage/service/MassageService.java
  src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/enumType/Massage.java
  src/main/java/com/server/Dotori/model/member/enumType/SelfStudy.java
  src/test/java/com/server/Dotori/model/member/service/massage/MassageServiceTest.java
Labels: Enhancement, Code-Review, OK

#260 학생 규정위반 기록하기(부여) 살짝 수정
  src/main/java/com/server/Dotori/model/rule/controller/RuleController.java
  src/main/java/com/server/Dotori/model/rule/dto/FindRulesAndDatesDto.java
  src/main/java/com/server/Dotori/model/rule/dto/RulesCntAndDatesDto.java
  src/main/java/com/server/Dotori/model/rule/repository/RuleRepositoryCustomImpl.java
  src/main/java/com/server/Dotori/model/rule/service/RuleService.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
  src/test/java/com/server/Dotori/model/rule/service/RuleServiceTest.java
Labels: Code-Review, Correction, OK

#258 자습신청 금지, 금지취소 기능 개발
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/admin/AdminSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/councillor/CouncillorSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/controller/selfstudy/developer/DeveloperSelfStudyController.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyService.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
  src/main/java/com/server/Dotori/model/music/controller/member/MemberMusicController.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
Labels: Documentation, Enhancement, Code-Review, Requirements, OK

#262 MemberController 좀더 RESTFul 하게 변경
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
Labels: Correction, TODO, OK

#264 Member Controller,Service 부분 url, 메서드명, 주석 등등.. 개선
  src/main/java/com/server/Dotori/dev_config/GenerateMember.java
  src/main/java/com/server/Dotori/model/member/controller/MemberController.java
  src/main/java/com/server/Dotori/model/member/controller/email/EmailController.java
  src/main/java/com/server/Dotori/model/member/dto/AuthPasswordDto.java
  src/main/java/com/server/Dotori/model/member/dto/ChangePasswordDto.java
  src/main/java/com/server/Dotori/model/member/dto/ChangePasswordEmailCheckDto.java
  src/main/java/com/server/Dotori/model/member/dto/EmailCertificateDto.java
  src/main/java/com/server/Dotori/model/member/dto/EmailDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDeleteDto.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/dto/SendAuthKeyForChangePasswordDto.java
  src/main/java/com/server/Dotori/model/member/dto/SignInDto.java
  src/main/java/com/server/Dotori/model/member/dto/SignUpEmailCheckDto.java
  src/main/java/com/server/Dotori/model/member/dto/WithdrawlDto.java
  src/main/java/com/server/Dotori/model/member/service/MemberService.java
  src/main/java/com/server/Dotori/model/member/service/MemberServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailService.java
  src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
  src/test/java/com/server/Dotori/model/board/service/BoardServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/MemberServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/mainpage/MainPageServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/massage/MassageServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/point/PointServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/role/RoleServiceImplTest.java
  src/test/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceTest.java
  src/test/java/com/server/Dotori/model/member/service/studentinfo/StuInfoServiceTest.java
  src/test/java/com/server/Dotori/model/music/service/MusicServiceTest.java
  src/test/java/com/server/Dotori/model/rule/service/RuleServiceTest.java
  src/test/java/com/server/Dotori/security/SecurityTest.java
  src/test/java/com/server/Dotori/util/CurrentMemberUtilTest.java
Labels: Documentation, Code-Review, Correction, TODO

#265 자습신청 금지 학생 일주일 뒤에 자동으로 금지 해제
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/member/schedule/SelfStudySchedule.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
Labels: Documentation, Enhancement, Code-Review, Requirements, OK

#266 단일 학생 규정위반 정보 단일 조회 기능 개발
  src/main/java/com/server/Dotori/model/rule/controller/RuleController.java
  src/main/java/com/server/Dotori/model/rule/dto/FindIdAndRuleAndDateDto.java
  src/main/java/com/server/Dotori/model/rule/dto/FindRuleAndDateDto.java
  src/main/java/com/server/Dotori/model/rule/dto/FindViolationOfTheRuleResponseDto.java
  src/main/java/com/server/Dotori/model/rule/repository/RuleRepositoryCustom.java
  src/main/java/com/server/Dotori/model/rule/repository/RuleRepositoryCustomImpl.java
  src/main/java/com/server/Dotori/model/rule/service/RuleService.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
  src/test/java/com/server/Dotori/model/rule/service/RuleServiceTest.java
Labels: Enhancement, Code-Review, TODO, OK

#267 도토리 클라이언트 개발자들정보 서버 띄워질 때 회원가입시키는 로직 추가
  src/main/java/com/server/Dotori/dev_config/GenerateMember.java
Labels: Correction

#268 기숙사규정을 어긴 항목을 삭제하는 기능
  src/main/java/com/server/Dotori/model/rule/controller/RuleController.java
  src/main/java/com/server/Dotori/model/rule/service/RuleService.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
  src/test/java/com/server/Dotori/model/rule/service/RuleServiceTest.java
Labels: Enhancement, Code-Review, TODO, OK

#271 massage builder (CAN)추가
  src/main/java/com/server/Dotori/dev_config/GenerateMember.java
Labels: Hotfix, OK

#270 안마의자 신청 상세로직 추가 및 변경
  src/main/java/com/server/Dotori/exception/massage/MassageExceptionHandler.java
  src/main/java/com/server/Dotori/exception/massage/MassageExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageAlreadyException.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageCantRequestDateException.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageCantRequestTimeException.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageOverException.java
  src/main/java/com/server/Dotori/model/massage/controller/councillor/CouncillorMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/developer/DeveloperMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/member/MemberMassageController.java
  src/main/java/com/server/Dotori/model/massage/repository/MassageRepository.java
  src/main/java/com/server/Dotori/model/massage/schedule/MassageSchedule.java
  src/main/java/com/server/Dotori/model/massage/service/MassageService.java
  src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/Member.java
  src/main/java/com/server/Dotori/model/member/dto/MemberDto.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/Dotori/model/member/service/massage/MassageServiceTest.java
Labels: Code-Review, Correction, OK

#272 안마의자 신청 취소 로직 추가
  src/main/java/com/server/Dotori/exception/massage/MassageExceptionHandler.java
  src/main/java/com/server/Dotori/exception/massage/MassageExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/massage/controller/MassageExceptionController.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageNotAppliedStatusException.java
  src/main/java/com/server/Dotori/model/massage/controller/councillor/CouncillorMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/developer/DeveloperMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/member/MemberMassageController.java
  src/main/java/com/server/Dotori/model/massage/repository/MassageRepository.java
  src/main/java/com/server/Dotori/model/massage/service/MassageService.java
  src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/Dotori/model/member/service/massage/MassageServiceTest.java
Labels: Code-Review, Correction, OK

#273 안마의자 신청을 한 학생 전체 조회
  src/main/java/com/server/Dotori/exception/massage/MassageExceptionHandler.java
  src/main/java/com/server/Dotori/exception/massage/MassageExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/massage/controller/MassageExceptionController.java
  src/main/java/com/server/Dotori/exception/massage/exception/MassageNoTheresException.java
  src/main/java/com/server/Dotori/model/massage/controller/admin/AdminMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/councillor/CouncillorMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/developer/DeveloperMassageController.java
  src/main/java/com/server/Dotori/model/massage/dto/MassageStudentsDto.java
  src/main/java/com/server/Dotori/model/massage/service/MassageService.java
  src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
  src/test/java/com/server/Dotori/model/member/service/massage/MassageServiceTest.java
Labels: Code-Review, Correction, OK

#274 Rule ENUM 타입 축소
  src/main/java/com/server/Dotori/model/rule/enumType/Rule.java
  src/test/java/com/server/Dotori/model/rule/service/RuleServiceTest.java
Labels: Correction
