Repository Team-Ampersand/Dotori-server, pull requests merged in 2022-02, with the labels that each got.

#276 RuleViolation 날짜컬럼 추가
  src/main/java/com/server/Dotori/model/rule/RuleViolation.java
  src/main/java/com/server/Dotori/model/rule/controller/RuleController.java
  src/main/java/com/server/Dotori/model/rule/dto/FindIdAndRuleAndDateDto.java
  src/main/java/com/server/Dotori/model/rule/dto/FindRuleAndDateDto.java
  src/main/java/com/server/Dotori/model/rule/dto/FindViolationOfTheRuleResponseDto.java
  src/main/java/com/server/Dotori/model/rule/dto/RuleGrantDto.java
  src/main/java/com/server/Dotori/model/rule/dto/RulesCntAndDatesDto.java
  src/main/java/com/server/Dotori/model/rule/repository/RuleRepositoryCustomImpl.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
  src/test/java/com/server/Dotori/model/rule/service/RuleServiceTest.java
Labels: Code-Review, Correction

#275 안마의자 신청 상태, 토탈 카운트 조회 서비스 로직 추가
  src/main/java/com/server/Dotori/model/massage/controller/admin/AdminMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/councillor/CouncillorMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/developer/DeveloperMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/member/MemberMassageController.java
  src/main/java/com/server/Dotori/model/massage/service/MassageService.java
  src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
  src/test/java/com/server/Dotori/model/member/service/massage/MassageServiceTest.java
Labels: Code-Review, Correction, OK

#279 제약조건 @Valid 누락된 곳 추가
  src/main/java/com/server/Dotori/model/board/controller/admin/AdminBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/councillor/CouncillorBoardController.java
  src/main/java/com/server/Dotori/model/board/controller/developer/DeveloperBoardController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/admin/AdminStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/councillor/CouncillorStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/developer/DeveloperStuInfoController.java
  src/main/java/com/server/Dotori/model/member/controller/studentinfo/member/MemberStuInfoController.java
  src/main/java/com/server/Dotori/model/member/dto/MemberNameUpdateDto.java
  src/main/java/com/server/Dotori/model/member/dto/RoleUpdateDto.java
  src/main/java/com/server/Dotori/model/member/dto/StuNumUpdateDto.java
Labels: Code-Review

#282 안마의자 신청 전체조회시 APPLIED상태인 모두가 조회되는 점 fix
  src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/enumType/Massage.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
Labels: Hotfix, Correction

#283 규정위반 존재 여부를 확인하는 조건문 추가
  src/main/java/com/server/Dotori/model/rule/dto/RuleGrantDto.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
Labels: Correction, TODO

#284 규정관리 Exception 메세지 추가
  src/main/java/com/server/Dotori/exception/rule/RuleExceptionHandler.java
  src/main/java/com/server/Dotori/exception/rule/RuleExceptionHandlerImpl.java
  src/main/java/com/server/Dotori/exception/rule/controller/RuleExceptionController.java
  src/main/java/com/server/Dotori/exception/rule/exception/RuleNoHistoryException.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
  src/main/resources/i18n/exception_en.yml
  src/main/resources/i18n/exception_ko.yml
Labels: Enhancement, OK

#285 안마의자 부분 주석 작성
  src/main/java/com/server/Dotori/model/massage/controller/admin/AdminMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/councillor/CouncillorMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/developer/DeveloperMassageController.java
  src/main/java/com/server/Dotori/model/massage/controller/member/MemberMassageController.java
  src/main/java/com/server/Dotori/model/massage/schedule/MassageSchedule.java
  src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
Labels: Documentation, OK

#286 메인페이지에서 권한 별 규정위반 조회
  src/main/java/com/server/Dotori/model/rule/controller/admin/AdminRuleController.java
  src/main/java/com/server/Dotori/model/rule/controller/councillor/CouncillorRuleController.java
  src/main/java/com/server/Dotori/model/rule/controller/developer/DeveloperRuleController.java
  src/main/java/com/server/Dotori/model/rule/controller/member/MemberRuleController.java
  src/main/java/com/server/Dotori/model/rule/service/RuleService.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
Labels: TODO, OK

#287 admin 권한에 상태,카운트 조회 controller 추가
  src/main/java/com/server/Dotori/model/massage/controller/admin/AdminMassageController.java
Labels: Hotfix, Correction

#290 기존에 있는 학생정보 조회 다시 api 제작
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryCustom.java
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/rule/controller/admin/AdminRuleController.java
  src/main/java/com/server/Dotori/model/rule/dto/FindStusDto.java
  src/main/java/com/server/Dotori/model/rule/service/RuleService.java
  src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
Labels: Correction

#291 [Hofix] 규정위반 학생 이름 검색 입력값 조건 변경 (한글자만으로 검색 가능), 컨트롤러 이름 중복 문제 해결
  src/main/java/com/server/Dotori/model/member/repository/member/MemberRepositoryImpl.java
  src/main/java/com/server/Dotori/model/rule/controller/councillor/CouncillorRuleController.java
  src/main/java/com/server/Dotori/model/rule/controller/developer/DeveloperRuleController.java
  src/main/java/com/server/Dotori/model/rule/controller/member/MemberRuleController.java
Labels: Hotfix, Correction

#292 자습신청, 안마의자 신청 시간제약 해제
  src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
  src/main/java/com/server/Dotori/model/member/service/selfstudy/SelfStudyServiceImpl.java
Labels: Correction, OK
