Repository Team-Ampersand/Dotori-server, pull requests merged in 2022-07, with the labels that each got.

#383 naming
  .github/workflows/cd.yml
Labels: OK

#387 prod환경 cd 도입
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/prod.yml
  appspec.yml
  scripts/deploy.sh
Labels: TODO, Requirements, OK

#391 @NoArgsConstructor 어노테이션이 없어서 JSON parsing안되던거 수정
  src/main/java/com/server/Dotori/domain/self_study/dto/SelfStudyCheckDto.java
Labels: Bug, Hotfix, OK

#392 Cors설정에 patch메소드 추가
  src/main/java/com/server/Dotori/global/config/web/WebConfig.java
Labels: Bug, Hotfix
